version: '3.9'

services:
  postgres:
    container_name: postgres
    image: registry.gitlab.com/dalibo/postgresql_anonymizer:stable
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
