name: Lab 1

on:
  push:
    branches:
      - master
    paths:
      - lab1.md
      - .github/workflows/lab1.yml
      - .github/workflows/render.yml

jobs:
  render:
    uses: ./.github/workflows/render.yml
    with:
      path: ./lab1.md
