on:
  push:
    branches:
      - master

jobs:
  render:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Render PlantUML
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: img
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

