name: 'Render reports'

on:
  workflow_call:
    inputs:
      template_values:
        type: string
        required: false
        default: '{}'
      path:
        type: string
        required: false
        default: './'

jobs:
  render:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: git pull --ff-only
      - name: Process templates
        if: ${{ inputs.template_values != '{}' }}
        run: |
          ENVSUBST_VARS=""
          for key in $(jq -n "$TEMPLATE_VALUES" | jq -r 'to_entries | map(.key) | .[]') ; do 
            value="$(jq -n "$TEMPLATE_VALUES" | jq -r ".$key")"
            ENVSUBST_VARS+="$key='$value' "
          done
          echo "Values: $ENVSUBST_VARS"
          
          for file in $(ls ${{ inputs.path }}) ; do
            ! [[ -f "$file" ]] && continue
            ! [[ $file =~ \.md ]] && continue
            bash -c "$ENVSUBST_VARS envsubst < $file > $file.tmp"
            mv $file.tmp $file
          done
        env:
          TEMPLATE_VALUES: ${{ inputs.template_values }}
      - name: Render PlantUML
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: img
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Render PDF from Markdown
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: ${{ inputs.path }}
          output_dir: pdf/
          images_dir: img
          # for example <img src="./img/file-name.png">
          image_import: img
          # Default is true, can set to false to only get PDF files
          build_html: false
      - name: Commit rendered PDFs
        run: |
          git config --global user.name 'github-actions bot'
          git config --global user.email 'kuzznya@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add pdf/
          git commit -m "Publish rendered PDFs"
          git push
